allowBuilds:
  esbuild: true
  netlify-cli: true
  sharp: true
  unix-dgram: true
minimumReleaseAgeExclude:
  - '@sveltejs/acorn-typescript@1.0.10'
  - '@types/node@25.9.1'
  - '@vitest/coverage-v8@4.1.7'
  - '@vitest/expect@4.1.7'
  - '@vitest/mocker@4.1.7'
  - '@vitest/pretty-format@4.1.7'
  - '@vitest/runner@4.1.7'
  - '@vitest/snapshot@4.1.7'
  - '@vitest/spy@4.1.7'
  - '@vitest/utils@4.1.7'
  - svelte@5.55.9
  - vitest@4.1.7
overrides:
  cookie@<0.7.0: '>=0.7.0'
